# Generated by Django 5.1 on 2024-08-30 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Entry', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
