# Generated by Django 5.1 on 2024-09-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_entry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='caegory',
            new_name='category',
        ),
    ]
